In [2]:
import pandas as pd

In [3]:
df = pd.read_json('train.json')
df.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

# working with sql

In [4]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in C:\Users\user\anaconda3\Lib\site-packages (2.2.9)

In [5]:
import mysql.connector

In [6]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="world",
  port=3307
)

print()

In [7]:
mycursor = mydb.cursor()
mycursor.execute("SHOW TABLES")

for table in mycursor:
    print(table)

('city',)
('country',)
('countrylanguage',)

In [8]:
df_sql = pd.read_sql_query("SELECT * FROM city", mydb)
df_sql.head()

C:\Users\user\AppData\Local\Temp\ipykernel_8612\247828308.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sql = pd.read_sql_query("SELECT * FROM city", mydb)

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

# python

In [15]:
import pandas as pd

# Hum bina kisi internet ke khud ka movies data bana rahe hain
custom_data = {
    'id':[1,3,5,2,4],
    'title': ['The Shawshank Redemption', 'The Godfather', 'The Godfather Part II', 'Dilwale Dulhania Le Jayenge', 'The Lord of the Rings'],
    'release_date': ['1994-09-23', '1972-03-14', '1974-12-20', '1995-10-20', '2003-12-17'],
    'vote_average': [8.7, 8.7, 8.6, 8.6, 8.5],
    'vote_count': [21811, 16203, 9811, 3731, 20424]
}

# Isko DataFrame (Table) mein badal diya, 
df_movies = pd.DataFrame(custom_data)

# Movies dekhne ke liye
df_movies.head()

   id                        title release_date  vote_average  vote_count
0   1     The Shawshank Redemption   1994-09-23           8.7       21811
1   3                The Godfather   1972-03-14           8.7       16203
2   5        The Godfather Part II   1974-12-20           8.6        9811
3   2  Dilwale Dulhania Le Jayenge   1995-10-20           8.6        3731
4   4        The Lord of the Rings   2003-12-17           8.5       20424

In [16]:
import pandas as pd

In [ ]:
import requests
import pandas as pd

url = "https://themoviedb.org"
response = requests.get(url)
df_movies = pd.DataFrame(response.json()['results'])
df_movies.head()

In [21]:
import json
import pandas as pd

# 1. real-world sample dataset hum direct memory mein rakh rahe hain
data_json = """
[
  {"id": 1, "cuisine": "greek", "ingredients": ["romaine lettuce", "black olives", "grape tomatoes"]},
  {"id": 2, "cuisine": "southern_us", "ingredients": ["plain flour", "ground pepper", "salt", "tomatoes"]},
  {"id": 3, "cuisine": "filipino", "ingredients": ["eggs", "pepper", "salt", "mayonnaise"]}
]
"""

# 2. JSON data ko Python formats mein convert karna
clean_data = json.loads(data_json)

# 3. Pandas DataFrame (Table) banana, 
df_movies = pd.DataFrame(clean_data)

# 4. Final Table ka preview dekhne ke liye
df_movies.head()

   id      cuisine                                      ingredients
0   1        greek  [romaine lettuce, black olives, grape tomatoes]
1   2  southern_us     [plain flour, ground pepper, salt, tomatoes]
2   3     filipino                 [eggs, pepper, salt, mayonnaise]